env:
  global:
    - CC_TEST_REPORTER_ID=3ab5b0fb05090ad19926f86753ee7e0bc4c76ffef8477a63c09bcbcba5737a1a
language: ruby
cache: bundler
bundler_args: --without production
services:
  - postgresql
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - RAILS_ENV=test bundle exec rails webpacker:compile
before_install:
  - gem update --system
  - gem install bundler
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

