version: '3'

volumes: 
  minio_data:

services:
  postgres:
    image: postgres:latest
    env_file: docker.env
    expose:
      - '5432'
  
  redis:
    image: redis:latest
    expose:
      - '6379'

  minio:
    image: minio/minio:RELEASE.2020-05-16T01-33-21Z
    volumes:
      - minio_data:/data:rw
    ports:
      - '9000:9000'
    env_file: docker.env
    command: server /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  web:
    build: .
    command: ['bash', 'docker/rails_web.sh']
    ports:
      - '3000:3000'
    depends_on:
      - postgres
      - redis
      - minio
    volumes:
      - .:/geneac
    env_file: docker.env
  
  worker:
    build: .
    command: ['bash', 'docker/rails_worker.sh']
    depends_on:
      - postgres
      - redis
      - minio
    volumes:
      - .:/geneac
    env_file: docker.env
