# config/app.yml for rails-settings-cached
defaults: &defaults
  show_recent_updates: true 
  require_login: false
  restrict_living_info: true

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
